name: Android Build Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
jobs:
  create_version_name_and_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: last_tag
        run: |
          LAST_TAG=$(git tag --sort=committerdate | tail -1)
          if [ -z "$LAST_TAG" ]; then
              echo "No tags found in the repository. create default tag 1.0.0"
              echo "LAST_TAG=1.0.0" >> $GITHUB_OUTPUT
          else
              echo "LAST_TAG=$LAST_TAG" >> $GITHUB_OUTPUT
          fi

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.last_tag.outputs.LAST_TAG }}
          level: patch

      - name: "Set output"
        id: set-output
        run: |
          echo "version_name=${{ steps.bump-semver.outputs.new_version }}" >> $GITHUB_OUTPUT
          
          IFS='.' read -r major minor patch <<< "${{ steps.bump-semver.outputs.new_version }}"
          version_code=$((major * 100 + minor * 10 + patch))
          
          echo "version_code=${version_code}" >> $GITHUB_OUTPUT
      - name: "Print output"
        run: |
          echo -e "Version name is: \n ${{ steps.set-output.outputs.version_name }}"
          echo -e "Version code is: \n ${{ steps.set-output.outputs.version_code }}"
    outputs:
      output_version_name: ${{ steps.set-output.outputs.version_name }}
      output_version_code: ${{ steps.set-output.outputs.version_code }}