name: Android Build Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
jobs:
  create_version_name_and_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: last_tag
        run: |
          LAST_TAG=$(git tag --sort=committerdate | tail -1)
          if [ -z "$LAST_TAG" ]; then
              echo "No tags found in the repository. create default tag 1.0.0"
              echo "LAST_TAG=1.0.0" >> $GITHUB_OUTPUT
          else
              echo "LAST_TAG=$LAST_TAG" >> $GITHUB_OUTPUT
          fi

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.last_tag.outputs.LAST_TAG }}
          level: patch

      - name: "Set output"
        id: set-output
        run: |
          echo "version_name=${{ steps.bump-semver.outputs.new_version }}" >> $GITHUB_OUTPUT
          
          IFS='.' read -r major minor patch <<< "${{ steps.bump-semver.outputs.new_version }}"
          version_code=$((major * 100 + minor * 10 + patch))
          
          echo "version_code=${version_code}" >> $GITHUB_OUTPUT
      - name: "Print output"
        run: |
          echo -e "Version name is: \n ${{ steps.set-output.outputs.version_name }}"
          echo -e "Version code is: \n ${{ steps.set-output.outputs.version_code }}"
    outputs:
      output_version_name: ${{ steps.set-output.outputs.version_name }}
      output_version_code: ${{ steps.set-output.outputs.version_code }}


  build_source_and_deploy:
    needs: [ create_version_name_and_code ]
    env:
      VERSION_NAME: ${{ needs.create_version_name_and_code.outputs.output_version_name }}
      VERSION_CODE: ${{ needs.create_version_name_and_code.outputs.output_version_code }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

#      - name: Bump Version
#        uses: chkfung/android-version-actions@v1.2.3
#        with:
#          gradlePath: app/build.gradle
#          versionCode: ${{ env.VERSION_CODE }}
#          versionName: ${{ env.VERSION_NAME }}

      - name: Create Google Services JSON File & KeyProperties File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
#          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: | 
          echo $GOOGLE_SERVICES_JSON | openssl base64 -d -out ./setupci/app/google-services.json
#          echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json


      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: "assembleRelease bundleRelease"

      - uses: r0adkll/sign-android-release@v1
        name: Sign app Apk file
        id: sign_apk_file
        with:
          releaseDirectory: setupci/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - uses: r0adkll/sign-android-release@v1
        name: Sign app Aab file
        id: sign_aab_file
        with:
          releaseDirectory: mchatfirebase/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mchat_${{ env.VERSION_NAME }}_${{ env.VERSION_CODE }}
          path: ${{steps.sign_apk_file.outputs.signedReleaseFile}}

      - name: Upload and Distribute App
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          file: ${{ steps.sign_apk_file.outputs.signedReleaseFile }}
          groups: 'test'
          #releaseNotes: 'This is a test release'

      - name: Push Tag
        run: |
          git config user.name loctran.dev
          git config user.email quangloc507@gmail.com
          git tag ${{ env.VERSION_NAME }}
          git push --tags